---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "shipping_service"
  name: "shipping-servic"
spec:
  ports:
  - name: "port-1-shipping"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
  selector:
    app: "shipping_service"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "shipping_service"
  name: "shipping-servic-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "shipping_service"
  template:
    metadata:
      labels:
        app: "shipping_service"
    spec:
      containers:
      - image: "bookstorecw1/shipping-service:latest"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "shipping-servic-deployment"
        env:
          - name: DB_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                key: DB_SERVICE_URL
                name: cm-book-store-cb
        ports:
        - containerPort: 9090
          name: "port-1-shipping"
          protocol: "TCP"
        - containerPort: 9091
          name: health
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 15
          periodSeconds: 30
          failureThreshold: 5
          successThreshold: 1
          httpGet:
            port: health
            path: /liveness
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
      nodeSelector: {}
      restartPolicy: Always
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "shipping_service"
  name: "shipping-servic"
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "shipping-servic-deployment"
  targetCPUUtilizationPercentage: 50
