name: Perform rolling update on cluster

on:
  workflow_dispatch:
  push:
      branches:
          - 'dev'
          - 'stage'
          - 'prod'
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: Extract cluster name
      shell: bash
      run: |
        if [[ "${GITHUB_REF#refs/heads/}" = "dev"  ]]
        then
          echo "::set-output name=cluster-name::book-store-cluster-dev"
        elif [[ "${GITHUB_REF#refs/heads/}" = "stage"  ]]
        then
          echo "::set-output name=cluster-name::book-store-cluster-stage"
        elif [[ "${GITHUB_REF#refs/heads/}" = "prod"  ]]
        then
          echo "::set-output name=cluster-name::book-store-cluster-prod"
        elif [[ "${GITHUB_REF#refs/heads/}" = "master"  ]]
        then
          echo "::set-output name=cluster-name::book-store-cluster"
        else
          echo "branch is not supported"
          exit 1
        fi
      id: cluster
    - name: AZURE LOGIN
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Configure AKS
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: '${{steps.cluster.outputs.cluster-name}}'
        resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
    - name: 'Install Kustomize'
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    - name: 'Run Kustomize'
      run: |
          sed -i 's/YOUR_PASSWORD/${{ secrets.MYSQL_PASSWORD }}/g' deployment/kustomization.yaml
          kustomize build deployment > final.yaml
    - name: 'Deploy pods'
      run: |
          kubectl apply -f final.yaml
          kubectl get svc istio-ingressgateway -n istio-system